import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const brazilianFoods = [
  // Café da manhã brasileiro
  {
    name: 'Pão Francês',
    category: 'paes',
    calories: 300,
    protein: 9.4,
    carbs: 58.6,
    fat: 3.1,
    fiber: 2.3,
    servingSize: 50,
    servingUnit: 'unidade',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Pão de Queijo',
    category: 'paes',
    calories: 335,
    protein: 6.8,
    carbs: 42.5,
    fat: 15.2,
    fiber: 1.2,
    servingSize: 30,
    servingUnit: 'unidade',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Tapioca',
    category: 'paes',
    calories: 358,
    protein: 0.6,
    carbs: 88.7,
    fat: 0.3,
    fiber: 0.9,
    servingSize: 100,
    servingUnit: 'unidade',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Café com Leite',
    category: 'bebidas',
    calories: 55,
    protein: 3.2,
    carbs: 5.8,
    fat: 2.2,
    servingSize: 200,
    servingUnit: 'ml',
    isBrazilian: true,
    isVerified: true,
  },

  // Pratos típicos
  {
    name: 'Feijoada Completa',
    category: 'pratos_principais',
    calories: 250,
    protein: 15.3,
    carbs: 18.5,
    fat: 13.2,
    fiber: 6.5,
    sodium: 580,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Arroz Branco Cozido',
    category: 'graos',
    calories: 130,
    protein: 2.7,
    carbs: 28.1,
    fat: 0.3,
    fiber: 0.4,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: false,
    isVerified: true,
  },
  {
    name: 'Feijão Preto Cozido',
    category: 'graos',
    calories: 77,
    protein: 4.5,
    carbs: 13.6,
    fat: 0.5,
    fiber: 4.5,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: false,
    isVerified: true,
  },
  {
    name: 'Farofa',
    category: 'acompanhamentos',
    calories: 365,
    protein: 3.5,
    carbs: 76.9,
    fat: 3.3,
    fiber: 2.1,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Coxinha de Frango',
    category: 'salgados',
    calories: 280,
    protein: 8.5,
    carbs: 32.4,
    fat: 12.8,
    servingSize: 80,
    servingUnit: 'unidade',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Pastel de Carne',
    category: 'salgados',
    calories: 295,
    protein: 7.2,
    carbs: 28.6,
    fat: 16.5,
    servingSize: 100,
    servingUnit: 'unidade',
    isBrazilian: true,
    isVerified: true,
  },

  // Frutas brasileiras
  {
    name: 'Açaí Puro',
    category: 'frutas',
    calories: 58,
    protein: 3.8,
    carbs: 6.2,
    fat: 3.9,
    fiber: 2.6,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Açaí com Guaraná (Tigela)',
    category: 'sobremesas',
    calories: 210,
    protein: 2.5,
    carbs: 38.5,
    fat: 5.2,
    fiber: 3.5,
    servingSize: 300,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Cupuaçu',
    category: 'frutas',
    calories: 49,
    protein: 1.5,
    carbs: 11.8,
    fat: 0.2,
    fiber: 1.7,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Jabuticaba',
    category: 'frutas',
    calories: 45,
    protein: 0.6,
    carbs: 11.5,
    fat: 0.1,
    fiber: 1.8,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Caju',
    category: 'frutas',
    calories: 43,
    protein: 1.0,
    carbs: 10.3,
    fat: 0.2,
    fiber: 1.7,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },

  // Doces brasileiros
  {
    name: 'Brigadeiro',
    category: 'doces',
    calories: 380,
    protein: 5.5,
    carbs: 58.2,
    fat: 14.8,
    servingSize: 20,
    servingUnit: 'unidade',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Beijinho',
    category: 'doces',
    calories: 365,
    protein: 4.8,
    carbs: 62.5,
    fat: 12.3,
    servingSize: 20,
    servingUnit: 'unidade',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Pudim de Leite',
    category: 'sobremesas',
    calories: 195,
    protein: 5.2,
    carbs: 32.8,
    fat: 5.5,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Quindim',
    category: 'doces',
    calories: 285,
    protein: 6.8,
    carbs: 45.2,
    fat: 9.5,
    servingSize: 50,
    servingUnit: 'unidade',
    isBrazilian: true,
    isVerified: true,
  },

  // Bebidas brasileiras
  {
    name: 'Guaraná Antarctica',
    brand: 'Antarctica',
    category: 'bebidas',
    calories: 40,
    protein: 0,
    carbs: 10.6,
    fat: 0,
    sugar: 10.6,
    servingSize: 100,
    servingUnit: 'ml',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Suco de Caju Natural',
    category: 'bebidas',
    calories: 39,
    protein: 0.7,
    carbs: 9.5,
    fat: 0.2,
    servingSize: 200,
    servingUnit: 'ml',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Mate Leão',
    brand: 'Leão',
    category: 'bebidas',
    calories: 28,
    protein: 0,
    carbs: 7.2,
    fat: 0,
    sugar: 7.2,
    servingSize: 100,
    servingUnit: 'ml',
    isBrazilian: true,
    isVerified: true,
  },

  // Alimentos comuns
  {
    name: 'Banana Prata',
    category: 'frutas',
    calories: 98,
    protein: 1.3,
    carbs: 26.0,
    fat: 0.1,
    fiber: 2.0,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: false,
    isVerified: true,
  },
  {
    name: 'Ovo Cozido',
    category: 'proteinas',
    calories: 155,
    protein: 13.0,
    carbs: 1.1,
    fat: 10.6,
    servingSize: 50,
    servingUnit: 'unidade',
    isBrazilian: false,
    isVerified: true,
  },
  {
    name: 'Peito de Frango Grelhado',
    category: 'proteinas',
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: false,
    isVerified: true,
  },
  {
    name: 'Batata Doce Cozida',
    category: 'vegetais',
    calories: 77,
    protein: 0.6,
    carbs: 18.4,
    fat: 0.1,
    fiber: 3.0,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: false,
    isVerified: true,
  },
  {
    name: 'Mandioca Cozida',
    category: 'vegetais',
    calories: 125,
    protein: 0.6,
    carbs: 30.1,
    fat: 0.3,
    fiber: 1.6,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Queijo Minas Frescal',
    category: 'laticinios',
    calories: 264,
    protein: 17.4,
    carbs: 3.8,
    fat: 20.8,
    sodium: 390,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
  {
    name: 'Requeijão Cremoso',
    category: 'laticinios',
    calories: 235,
    protein: 6.8,
    carbs: 4.5,
    fat: 22.0,
    servingSize: 100,
    servingUnit: 'g',
    isBrazilian: true,
    isVerified: true,
  },
];

async function seed() {
  console.log('🌱 Iniciando seed do banco de dados...');

  try {
    // Limpar alimentos existentes (cuidado em produção!)
    await prisma.food.deleteMany({});
    console.log('🗑️  Alimentos anteriores removidos');

    // Inserir alimentos brasileiros
    for (const food of brazilianFoods) {
      await prisma.food.create({
        data: food,
      });
    }

    console.log(`✅ ${brazilianFoods.length} alimentos inseridos com sucesso!`);
    console.log('🇧🇷 Alimentos brasileiros típicos incluídos!');
  } catch (error) {
    console.error('❌ Erro ao fazer seed:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seed();
